name: flutter_consumer_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.0.6 <4.0.0'
  # 3.24.0 

dependencies:
  flutter:
    sdk: flutter
  flutter_otp_text_field: ^1.1.1
  # keyboard_dismisser: ^3.0.0
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^6.0.1
  email_validator: ^2.1.17
  flutter_bloc: ^8.1.3
  # dio: ^5.3.2
  http: ^1.1.0
  equatable: ^2.0.5
  shared_preferences: ^2.2.1
  geocoding: ^2.1.0
  geolocator: ^10.0.1
  intl: ^0.18.1
  # chips_choice: ^3.0.1
  image_picker: ^1.0.4
  multi_image_picker_plus: ^0.0.5
  # multi_image_picker: ^4.7.14
  file_picker: ^5.5.0
  share_whatsapp: ^1.0.2
  # share: ^2.0.1
  carousel_slider: ^4.2.1
  google_maps_flutter: ^2.1.0
  # flutter_polyline_points: ^2.0.0
  # location: ^5.0.3
  flutter_svg: ^2.0.9
  # typicons_flutter: ^0.5.0
  circular_countdown_timer: ^0.2.3
  mixpanel_flutter: ^2.1.1
  card_swiper: ^3.0.1
  json_annotation:
  device_info_plus: ^9.1.0
  # flutter_swiper_view: ^1.1.8f
  either_dart: ^1.0.0
  get_it: ^7.6.4
  # redacted: ^1.0.11
  # network_info_plus: ^4.1.0
  connectivity_plus: ^3.0.3
  internet_connection_checker: ^1.0.0+1
  simple_gradient_text: ^1.3.0
  meta: ^1.9.1
  bloc: ^8.1.2
  buttons_tabbar: ^1.3.8
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1
  # booking_calendar: ^1.1.10
  table_calendar: ^3.0.9
  flutter_staggered_grid_view: ^0.4.0
  # dots_indicator: ^3.0.0
  # visibility_detector: ^0.4.0+2
  # video_player: ^2.8.1
  # chewie: ^1.7.1
  flutter_story_view: ^0.0.3
  # toggle_switch: ^2.1.0
  # chatview: ^1.3.1
  razorpay_flutter: ^1.3.5
  maps_launcher: ^2.2.0
  add_2_calendar: ^3.0.1
  # fluttertoast: ^8.2.4
  story_view: ^0.16.0
  after_layout: ^1.2.0
  # emoji_picker_flutter: ^1.6.3
  cached_network_image: ^3.3.0
  # amplify_flutter: ^1.6.1
  # amplify_storage_s3: ^1.6.1
  sizer: ^2.0.15
  percent_indicator: ^4.2.3
  # flutter_profile_picture: ^2.0.0
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^18.0.1



  
  flutter_initicon: ^3.0.0+1
  flutter_widget_from_html: 
  # flutter_widget_from_html: ^0.14.11
  freezed_annotation: ^2.4.1
  page_transition: ^2.1.0
  flutter_screenutil: ^5.9.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  encrypt: ^5.0.3
  flutter_xlider: ^3.5.0
  flutter_html: ^3.0.0-beta.2
  syncfusion_flutter_pdfviewer:
  # syncfusion_flutter_pdfviewer: ^26.1.41
  # syncfusion_flutter_pdfviewer: ^27.1.55

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1
  freezed: ^2.4.6
flutter_icons:
  image_path: "icons/megmologo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/tier_images/
    - assets/images/cities/
    - assets/photos/
  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/JosefinSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/JosefinSans-Light.ttf
          weight: 300
        - asset: assets/fonts/JosefinSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/JosefinSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/JosefinSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/JosefinSans-Thin.ttf
          weight: 100
    - family:  AppIcons
      fonts:
        - asset: assets/icons/AppIcons.ttf