// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcHUvNjwWGI_PhfCLBGl3YbzoAHpOG-kQ',
    appId: '1:184993598208:web:1ae3a669ece4e28b7641e5',
    messagingSenderId: '184993598208',
    projectId: 'wigglypet-app',
    authDomain: 'wigglypet-app.firebaseapp.com',
    storageBucket: 'wigglypet-app.firebasestorage.app',
    measurementId: 'G-HLPPZ3WRB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC1YL4pE2txzWDaOhMSlZTPBmUluWp_Yw',
    appId: '1:184993598208:android:685b379f2f06c99b7641e5',
    messagingSenderId: '184993598208',
    projectId: 'wigglypet-app',
    storageBucket: 'wigglypet-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK3lA_FJmkOtwk7HvOcVT6baQjp1vhMzs',
    appId: '1:184993598208:ios:b3331bb2df7927407641e5',
    messagingSenderId: '184993598208',
    projectId: 'wigglypet-app',
    storageBucket: 'wigglypet-app.firebasestorage.app',
    iosClientId: '184993598208-f94j5e8bckn8rcdqej8ne98cq8k38qno.apps.googleusercontent.com',
    iosBundleId: 'com.test11.consumer',
  );

}