// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMsxS87osWPpcmKpuQp9krad_PexDMFtA',
    appId: '1:102836287134:web:64a707e7c1948ba8992d8f',
    messagingSenderId: '102836287134',
    projectId: 'megmo-47094',
    authDomain: 'megmo-47094.firebaseapp.com',
    storageBucket: 'megmo-47094.appspot.com',
    measurementId: 'G-8L00HMJ9P7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu5826huc5cTdFljvA_2pczD7n2TFtYoI',
    appId: '1:102836287134:android:a1106d01da4b84b6992d8f',
    messagingSenderId: '102836287134',
    projectId: 'megmo-47094',
    storageBucket: 'megmo-47094.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMxYKYdXkG-IvYXoVk7XPIYGScFIcqmhY',
    appId: '1:102836287134:ios:d9ed9d6f0cf6860f992d8f',
    messagingSenderId: '102836287134',
    projectId: 'megmo-47094',
    storageBucket: 'megmo-47094.appspot.com',
    iosClientId: '102836287134-dn2elbp6e88e3qfjtd40fb46jaq6q5ri.apps.googleusercontent.com',
    iosBundleId: 'com.megmo.consumer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMxYKYdXkG-IvYXoVk7XPIYGScFIcqmhY',
    appId: '1:102836287134:ios:b336c867c5beb8b0992d8f',
    messagingSenderId: '102836287134',
    projectId: 'megmo-47094',
    storageBucket: 'megmo-47094.appspot.com',
    iosClientId: '102836287134-popl5466ojb6kmgimkalspjk7lv81lor.apps.googleusercontent.com',
    iosBundleId: 'com.megmo.consumer.RunnerTests',
  );
}
