/// Flutter icons AppIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';
  static const String? _kFontPkg = null;

  static const IconData my_wallet = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mylocation = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData name = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData navigate_next = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifications = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData password = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData preferences = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData recents = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_1 = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData success = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toggle_off = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toggle_on = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trending_searches = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_a_photo = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData auto_detect_my_location = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bithdate = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book_again = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coins = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData error_circle = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData failed = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData external_link = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gender = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help_centre = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData liked_packages = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_on = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mark_chat_read = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mark_chat_unread = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData messages = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData my_bookings = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData my_chats = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData my_notifications = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData my_ratings = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData musicians = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nail_artists = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pet_tranier_groomers = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photographers = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData singers = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yoga_trainers = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData babysitter = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData henna_artists = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData makeup_artists = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData models = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chandigarh = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chennai = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delhi = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hyderabad = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kolkata = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pune = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mumbai = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ahmedabad = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bangalore = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
